[vars]
output_dir = "dist"

[tasks.build]
run = "flatpak run --install-deps-from=flathub org.flatpak.Builder --force-clean --user --install {{vars.output_dir}} io.github.themulhima.Lumafly.yaml"

[tasks.check]
run = "flatpak run --install-deps-from=flathub org.flathub.flatpak-external-data-checker io.github.themulhima.Lumafly.yaml"
